Separate assembly for pipeline abstraction
wenzhang-unity/RenderStream-Unity pull request #15
Opened 2023-02-28 19:33 UTC by mark-beiline

2023-03-03 17:55 UTC, wenzhang-unity commented
You should briefly describe why we need this PR. The lack of a PR template doesn't mean that you can just leave it blank.

2023-03-06 14:17 UTC, wenzhang-unity requested changes

2023-03-06 14:17 UTC, wenzhang-unity commented on DisguiseUnityRenderStream/Runtime/PipelineAbstraction/DepthCopy.cs
> +    public class DepthCopy
With this new assembly separation, you don't have to make any of the classes `public`. You can just use the `InternalsVisibleTo` attribute in the `Diguise.RenderStream` assembly.

2023-03-16 15:51 UTC, mark-beiline commented on DisguiseUnityRenderStream/Editor/Disguise.RenderStream.Editor.asmdef
> +        "Disguise.RenderStream.PipelineAbstraction",
This is only for the `AddAlwaysIncludedShader` calls in `DisguiseRenderStreamBuildPreProcessor.OnPreprocessBuild`.

2023-04-03 14:42 UTC, wenzhang-unity approved these changes

2023-04-03 16:13 UTC, merged